protected/models/Comment.php
<?php

class Comment extends CActiveRecord
{
    /**
     * The followings are the available columns in table 'tbl_comment':
     * @var integer $id
     * @var string $content
     * @var integer $status
     * @var integer $create_time
     * @var string $author
     * @var string $email
     * @var string $url
     * @var integer $post_id
     */
    const STATUS_PENDING=1;
    const STATUS_APPROVED=2;

    /**
     * Returns the static model of the specified AR class.
     * @return CActiveRecord the static model class
     */
    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{comment}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('content, author, email', 'required'),
            array('author, email, url', 'length', 'max'=>128),
            array('email','email'),
            array('url','url'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'post' => array(self::BELONGS_TO, 'Post', 'post_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('blog','ID'),
            'content' => Yii::t('blog','Comment'),
            'status' => Yii::t('blog','Status'),
            'create_time' => Yii::t('blog','Created On'),
            'author' => Yii::t('blog','Name'),
            'email' => Yii::t('blog','Email'),
            'url' => Yii::t('blog','Website'),
            'post_id' => Yii::t('blog','Post'),
        );
    }

    /**
     * Approves a comment.
     */
    public function approve()
    {
        $this->status=Comment::STATUS_APPROVED;
        return $this->update(array('status'));
    }

    /**
     * @param Post the post that this comment belongs to. If null, the method
     * will query for the post.
     * @return string the permalink URL for this comment
     */
    public function getUrl($post=null)
    {
        if($post===null)
            $post=$this->post;
        return $post->url.'#c'.$this->id;
    }

    /**
     * @return string the hyperlink display for the current comment's author
     */
    public function getAuthorLink()
    {
        if(!empty($this->url))
            return CHtml::link(CHtml::encode($this->author),$this->url);
        else
            return CHtml::encode($this->author);
    }

    /**
     * @return integer the number of comments that are pending approval
     */
    public function getPendingCommentCount()
    {
        return $this->count('status='.self::STATUS_PENDING);
    }

    /**
     * @param integer the maximum number of comments that should be returned
     * @return array the most recently added comments
     */
    public function findRecentComments($limit=10)
    {
        return $this->with('post')->findAll(array(
            'condition'=>'t.status='.self::STATUS_APPROVED,
            'order'=>'t.create_time DESC',
            'limit'=>$limit,
        ));
    }

    /**
     * This is invoked before the record is saved.
     * @return boolean whether the record should be saved.
     */
    protected function beforeSave()
    {
        if(parent::beforeSave())
        {
            if($this->isNewRecord)
                $this->create_time=time();
            return true;
        }
        else
            return false;
    }
}

protected/controllers/CommentController.php
<?php

class CommentController extends Controller
{
	public $layout='column2';

	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated users to access all actions
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel();
		if(isset($_POST['ajax']) && $_POST['ajax']==='comment-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
		if(isset($_POST['Comment']))
		{
			$model->attributes=$_POST['Comment'];
            if($model->save()) {
                Yii::app()->user->setFlash('success', Yii::t('blog','<strong>Update Comment</strong> You successfully updated the comment.'));
                $this->redirect(array('index')); 
            }
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
            if($this->loadModel()->delete())
                Yii::app()->user->setFlash('success',Yii::t('blog','<strong>Delete Comment</strong> The comment has been deleted.'));

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_POST['ajax']))
				$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Comment', array(
			'criteria'=>array(
				'with'=>'post',
				'order'=>'t.status, t.create_time DESC',
			),
		));

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Approves a particular comment.
	 * If approval is successful, the browser will be redirected to the comment index page.
	 */
	public function actionApprove()
	{
		if(Yii::app()->request->isPostRequest)
		{
			$comment=$this->loadModel();
            if($comment->approve())
                Yii::app()->user->setFlash('success', Yii::t('blog','<strong>Approve Comment</strong> You successfully approved the comment.'));                
			$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=Comment::model()->findbyPk($_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}
}

protected/views/comment/_form.php
<div class="form">

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'=>'comment-form',
	'enableAjaxValidation'=>true,
    'htmlOptions'=>array('class'=>'well'),
)); ?>

        <p class="note"><?php printf(CHtml::encode(Yii::t('site', 'Fields with %s are required.')), '<span class="required">*</span>'); ?></p>

	<?php echo $form->textFieldRow($model,'author',array('size'=>60,'maxlength'=>128)); ?>

	<?php echo $form->textFieldRow($model,'email',array('size'=>60,'maxlength'=>128)); ?>

	<?php echo $form->textFieldRow($model,'url',array('size'=>60,'maxlength'=>128)); ?>

	<?php echo $form->textAreaRow($model,'content',array('rows'=>6, 'cols'=>50)); ?>

    <div class="form-actions">
        <?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'submit', 'type'=>'primary', 'icon'=>'ok','label'=>$model->isNewRecord ? Yii::t('site','Submit') : Yii::t('site','Save'))); ?>
        <?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'reset', 'icon'=>'repeat','label'=>Yii::t('site','Reset'))); ?>
    </div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/comment/_view.php
<?php
$deleteJS = <<<DEL
$('.container').on('click','.time a.delete',function() {
    var th=$(this),
        container=th.closest('div.comment'),
        id=container.attr('id').slice(1);
    if(confirm('Are you sure you want to delete comment #'+id+'?')) {
        $.ajax({
            url:th.attr('href'),
            type:'POST'
        }).done(function(){container.slideUp()});
    }
    return false;
});
DEL;
Yii::app()->getClientScript()->registerScript('delete', $deleteJS);
?>
<div class="comment" id="c<?php echo $data->id; ?>">

    <?php echo CHtml::link("#{$data->id}", $data->url, array(
        'class'=>'cid',
        'title'=>'Permalink to this comment',
    )); ?>

    <div class="author">
        <?php echo $data->authorLink; ?> says on
        <?php echo CHtml::link(CHtml::encode($data->post->title), $data->post->url); ?>
    </div>

    <div class="time">
        <?php if($data->status==Comment::STATUS_PENDING): ?>
        <span class="pending"><?php echo CHtml::encode(Yii::t('blog','Pending approval')); ?></span>&nbsp;
            <?php echo CHtml::linkButton('<i class="icon-ok"></i>&nbsp;'.Yii::t('blog','Approve'), array(
                'submit'=>array('comment/approve','id'=>$data->id),
                'class'=>'btn btn-success btn-mini',

            )); ?>
        <?php endif; ?>
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'label'=>Yii::t('blog','Update'),
            'buttonType'=>'link',
            'url'=>array('comment/update','id'=>$data->id),
            //'type'=>'success', // null, 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
            'size'=>'mini', // null, 'large', 'small' or 'mini'
            'icon'=>'pencil',
        )); ?>
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'label'=>Yii::t('blog','Delete'),
            'buttonType'=>'link',
            'url'=>array('comment/delete','id'=>$data->id),
            'type'=>'danger', // null, 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
            'size'=>'mini', // null, 'large', 'small' or 'mini'
            'icon'=>'remove',
            'htmlOptions'=>array('class'=>'delete'),
        )); ?>
        <?php echo CHtml::encode(Yii::t('blog','written on {create_time}',array('{create_time}'=>Yii::app()->dateFormatter->formatDateTime($data->create_time, 'full','short')))); ?>
    </div>

    <div class="content">
        <?php echo nl2br(CHtml::encode($data->content)); ?>
    </div>

</div><!-- comment -->

protected/views/comment/index.php
<?php
$this->breadcrumbs=array(
	Yii::t('blog','Comments'),
);
?>

<h1>Comments</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/comment/update.php
<?php
$this->breadcrumbs=array(
	'Comments'=>array('index'),
	'Update Comment #'.$model->id,
);
?>

<h1>Update Comment #<?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>