protected/models/Post.php
<?php

class Post extends CActiveRecord
{
    /**
     * The followings are the available columns in table 'tbl_post':
     * @var integer $id
     * @var string $title
     * @var string $intro
     * @var string $content
     * @var string $tags
     * @var integer $status
     * @var integer $create_time
     * @var integer $update_time
     * @var integer $author_id
     */
    const STATUS_DRAFT=1;
    const STATUS_PUBLISHED=2;
    const STATUS_ARCHIVED=3;

    private $_oldTags;

    /**
     * Returns the static model of the specified AR class.
     * @return CActiveRecord the static model class
     */
    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{post}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('title, intro, content, status', 'required'),
            array('status', 'in', 'range'=>array(1,2,3)),
            array('title', 'length', 'max'=>128),
            array('tags', 'match', 'pattern'=>'/^[\w\s,]+$/', 'message'=>'Tags can only contain word characters.'),
            array('tags', 'normalizeTags'),

            array('intro, title, status', 'safe', 'on'=>'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'author' => array(self::BELONGS_TO, 'User', 'author_id'),
            'comments' => array(self::HAS_MANY, 'Comment', 'post_id', 'condition'=>'comments.status='.Comment::STATUS_APPROVED, 'order'=>'comments.create_time DESC'),
            'commentCount' => array(self::STAT, 'Comment', 'post_id', 'condition'=>'status='.Comment::STATUS_APPROVED),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id'            => Yii::t('blog','ID'),
            'title'         => Yii::t('blog','Title'),
            'intro'         => Yii::t('blog','Intro'),
            'content'       => Yii::t('blog','Content'),
            'tags'          => Yii::t('blog','Tags'),
            'status'        => Yii::t('blog','Status'),
            'create_time'   => Yii::t('blog','Createed On'),
            'update_time'   => Yii::t('blog','Updated On'),
            'author_id'     => Yii::t('blog','Author'),
        );
    }

    /**
     * @return string the URL that shows the detail of the post
     */
    public function getUrl()
    {
        return Yii::app()->createUrl('post/view', array(
            'id'=>$this->id,
            'title'=>$this->title,
        ));
    }

    /**
     * @return array a list of links that point to the post list filtered by every tag of this post
     */
    public function getTagLinks()
    {
        $links=array();
        foreach(Tag::string2array($this->tags) as $tag)
            $links[]=CHtml::link(CHtml::encode($tag), array('post/index', 'tag'=>$tag));
        return $links;
    }

    /**
     * Normalizes the user-entered tags.
     */
    public function normalizeTags($attribute,$params)
    {
        $this->tags=Tag::array2string(array_unique(Tag::string2array($this->tags)));
    }

    /**
     * Adds a new comment to this post.
     * This method will set status and post_id of the comment accordingly.
     * @param Comment the comment to be added
     * @return boolean whether the comment is saved successfully
     */
    public function addComment($comment)
    {
        if(Yii::app()->params['commentNeedApproval'])
            $comment->status=Comment::STATUS_PENDING;
        else
            $comment->status=Comment::STATUS_APPROVED;
        $comment->post_id=$this->id;
        return $comment->save();
    }

    /**
     * This is invoked when a record is populated with data from a find() call.
     */
    protected function afterFind()
    {
        parent::afterFind();
        $this->_oldTags=$this->tags;
    }

    /**
     * This is invoked before the record is saved.
     * @return boolean whether the record should be saved.
     */
    protected function beforeSave()
    {
        if(parent::beforeSave())
        {
            if($this->isNewRecord)
            {
                $this->create_time=$this->update_time=time();
                $this->author_id=Yii::app()->user->id;
            }
            else
                $this->update_time=time();
            return true;
        }
        else
            return false;
    }

    /**
     * This is invoked after the record is saved.
     */
    protected function afterSave()
    {
        parent::afterSave();
        Tag::model()->updateFrequency($this->_oldTags, $this->tags);
    }

    /**
     * This is invoked after the record is deleted.
     */
    protected function afterDelete()
    {
        parent::afterDelete();
        Comment::model()->deleteAll('post_id='.$this->id);
        Tag::model()->updateFrequency($this->tags, '');
    }

    /**
     * Retrieves the list of posts based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the needed posts.
     */
    public function search()
    {
        $criteria=new CDbCriteria;

        $criteria->compare('title',$this->title,true);

        $criteria->compare('status',$this->status);

        return new CActiveDataProvider('Post', array(
            'criteria'=>$criteria,
            'sort'=>array(
                'defaultOrder'=>'status, update_time DESC',
            ),
        ));
    }
    
    /**
     * @param integer the maximum number of posts that should be returned
     * @return array the most recently added posts
     */
    public function findRecentPosts($limit=10)
    {
        return $this->findAll(array(
            'condition'=>'t.status='.self::STATUS_PUBLISHED,
            'order'=>'t.create_time DESC',
            'limit'=>$limit,
        ));
    }

    /**
     * Find articles posted in this month
     * @return array the articles posted in this month
     */
    public function findArticlePostedThisMonth()
    {
            if (!empty($_GET['time'])) {
                    $month = date('n', $_GET['time']);
                    $year = date('Y', $_GET['time']);
                    if (!empty($_GET['pnc']) && $_GET['pnc'] == 'n') $month++;
                    if (!empty($_GET['pnc']) && $_GET['pnc'] == 'p') $month--;
            } else {
                    $month = date('n');
                    $year = date('Y');
            }

            return $this->findAll(array(
                    'condition'=>'create_time > :time1 AND create_time < :time2
                                    AND t.status='.self::STATUS_PUBLISHED,
                    'params'=>array(':time1' => mktime(0,0,0,$month,1,$year),
                                    ':time2' => mktime(0,0,0,$month+1,1,$year),
                            ),
                    'order'=>'t.create_time DESC',
            ));
    }

    /**
     * Returns an array of status descriptions, indexed by status codes
     *
     * @return mixed
     */
    public function getStatusOptions()
    {
        return array(
            self::STATUS_DRAFT      => Yii::t('blog','Draft'),
            self::STATUS_PUBLISHED  => Yii::t('blog','Published'),
            self::STATUS_ARCHIVED   => Yii::t('blog','Archived'),
        );
    }
}

protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	public $layout='column2';

    public $operations;

	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

    /**
     * Declares the behaviors.
     * @return array the behaviors
     */
    public function behaviors()
    {
        return array(
            'seo'=>'ext.seo.components.SeoControllerBehavior',
        );
    }
    
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to access 'index' and 'view' actions.
				'actions'=>array('index','view', 'search', 'postedInMonth'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated users to access all actions
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{
		$post=$this->loadModel();
		$comment=$this->newComment($post);

		$this->render('view',array(
			'model'=>$post,
			'comment'=>$comment,
		));
	}

    // {{{ actionPreview
    public function actionPreview()
    {
        $parser=new CMarkdownParser;
        echo $parser->safeTransform($_POST['Post'][$_GET['attribute']]);
    } // }}} 

    /**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Post;
		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel();
		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel()->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$criteria=new CDbCriteria(array(
			'condition'=>'status='.Post::STATUS_PUBLISHED,
			'order'=>'update_time DESC',
			'with'=>'commentCount',
		));
		if(isset($_GET['tag']))
			$criteria->addSearchCondition('tags',$_GET['tag']);

		$dataProvider=new CActiveDataProvider('Post', array(
			'pagination'=>array(
				'pageSize'=>Yii::app()->params['postsPerPage'],
			),
			'criteria'=>$criteria,
		));

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Post('search');
		if(isset($_GET['Post']))
			$model->attributes=$_GET['Post'];
		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Suggests tags based on the current user input.
	 * This is called via AJAX when the user is entering the tags input.
	 */
	public function actionSuggestTags()
	{
		if(isset($_GET['q']) && ($keyword=trim($_GET['q']))!=='')
		{
			$tags=Tag::model()->suggestTags($keyword);
			if($tags!==array())
				echo implode("\n",$tags);
		}
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
			{
				if(Yii::app()->user->isGuest)
					$condition='status='.Post::STATUS_PUBLISHED.' OR status='.Post::STATUS_ARCHIVED;
				else
					$condition='';
				$this->_model=Post::model()->findByPk($_GET['id'], $condition);
			}
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}

	/**
	 * Creates a new comment.
	 * This method attempts to create a new comment based on the user input.
	 * If the comment is successfully created, the browser will be redirected
	 * to show the created comment.
	 * @param Post the post that the new comment belongs to
	 * @return Comment the comment instance
	 */
	protected function newComment($post)
	{
		$comment=new Comment;
		if(isset($_POST['ajax']) && $_POST['ajax']==='comment-form')
		{
			echo CActiveForm::validate($comment);
			Yii::app()->end();
		}
		if(isset($_POST['Comment']))
		{
			$comment->attributes=$_POST['Comment'];
			if($post->addComment($comment))
			{
				if($comment->status==Comment::STATUS_PENDING)
					Yii::app()->user->setFlash('commentSubmitted','Thank you for your comment. Your comment will be posted once it is approved.');
				$this->refresh();
			}
		}
		return $comment;
	}
	/**
         * Sitewide search.
         * Shows a particular post searched.
         */
        public function actionSearch()
        {
		$search = new SiteSearchForm;
                
		if(isset($_POST['SiteSearchForm'])) {
			$search->attributes = $_POST['SiteSearchForm'];
			$_GET['searchString'] = $search->string;
		} else {
			$search->string = $_GET['searchString'];
		}
		
		$criteria = new CDbCriteria(array(
			'condition' => 'status='.Post::STATUS_PUBLISHED.' AND (title LIKE :keyword OR intro LIKE :keyword OR content LIKE :keyword)',
			'order' => 'create_time DESC',
			'params' => array(
				':keyword' => '%'.$search->string.'%',
			),
		));
                
		$postCount = Post::model()->count($criteria);
		$pages = new CPagination($postCount);
		$pages->pageSize = Yii::app()->params['postsPerPage'];
		$pages->applyLimit($criteria);
                
		$posts = Post::model()->findAll($criteria);
						    
		$this->render('found',array(
			'posts' => $posts,
			'pages' => $pages,
			'search' => $search,
		));

        }

        /**                                                                                                     
         * Collect posts issued on specific date                                                                
         */
        public function actionPostedOnDate()
        {
		$month = date('n', $_GET['time']);
		$date = date('j', $_GET['time']);
		$year = date('Y', $_GET['time']);

		$criteria = new CDbCriteria(array(
			'condition' => 'status='.Post::STATUS_PUBLISHED.' AND create_time > :time1 AND create_time < :time2',
			'order' => 'update_time DESC',
			'params' => array(
				':time1' => ($theDay = mktime(0,0,0,$month,$date,$year)),
				':time2' => mktime(0,0,0,$month,$date+1,$year)),
		));

		$pages = new CPagination(Post::model()->count($criteria));
		$pages->pageSize = Yii::app()->params['postsPerPage'];
		$pages->applyLimit($criteria);

		$posts = Post::model()->with('author')->findAll($criteria);

		$this->render('date',array(
			'posts' => $posts,
                        'pages' => $pages,
                        'theDay' => $theDay,
		));
        }

	/**
         * Collect posts issued in specific month
         */
        public function actionPostedInMonth()
        {
		$month = date('n', $_GET['time']);
		$year = date('Y', $_GET['time']);
		if ($_GET['pnc'] == 'n') $month++;
		if ($_GET['pnc'] == 'p') $month--;

		$criteria = new CDbCriteria(array(
			'condition' => 'status = '.Post::STATUS_PUBLISHED.' AND create_time > :time1 AND create_time < :time2',
			'order' => 'update_time DESC',
			'params' => array(
				':time1' => ($firstDay = mktime(0,0,0,$month,1,$year)),
				':time2' => mktime(0,0,0,$month+1,1,$year)),
		));

		$pages = new CPagination(Post::model()-> count($criteria));
		$pages->pageSize = Yii::app()->params['postsPerPage'];
		$pages->applyLimit($criteria);

		$posts = Post::model()->with('author')->findAll($criteria);

		$this->render('month',array(
			'posts' => $posts,
			'pages' => $pages,
			'firstDay' => $firstDay,
		));
        }
}

protected/views/post/_comments.php
<?php foreach($comments as $comment): ?>
<div class="comment" id="c<?php echo $comment->id; ?>">

	<?php echo CHtml::link("#{$comment->id}", $comment->getUrl($post), array(
		'class'=>'cid',
		'title'=>Yii::t('blog','Permalink to this comment'),
	)); ?>

	<div class="author">
		<?php printf( CHtml::encode(Yii::t('blog', '%s says:')), $comment->authorLink); ?>
	</div>

	<div class="time">
		<?php echo Yii::app()->dateFormatter->formatDateTime($comment->create_time, 'full','short'); ?>
	</div>

	<div class="content">
		<?php echo nl2br(CHtml::encode($comment->content)); ?>
	</div>

</div><!-- comment -->
<?php endforeach; ?>

protected/views/post/_form.php
<div class="form">

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'=>'post-form',
    'type'=>'horizontal',
    'focus'=>array($model,$model->isNewRecord ? 'title' : 'intro'),
)); ?>

    <p class="note"><?php printf(CHtml::encode(Yii::t('site', 'Fields with %s are required.')), '<span class="required">*</span>'); ?></p>

    <?php echo CHtml::errorSummary($model); ?>

    <?php echo $form->textFieldRow($model,'title',array('class'=>'span5','maxlength'=>128)); ?>

    <div class="control-group">
        <?php echo CHtml::activeLabelEx($model,'intro',array('class'=>'control-label')); ?>
        <div class="controls">
            <?php $this->widget('application.extensions.ddeditor-bs.DDEditor',array(
                'model'=>$model,
                'attribute'=>'intro',
                'previewRequest'=>'/post/preview',
                'htmlOptions'=>array('rows'=>7,'cssClass'=>'span6','style'=>'font-family:Courier', 'title'=>Yii::t('blog','Enter the intro text (you may use Mardown syntax)') ),
                'additionalSnippets'=>array(
                    Yii::t('onlinehelp','Icons')=>array(
                        '<i class="icon-star"></i>' => Yii::t('onlinehelp','Create New Item'),
                        '<i class="icon-eye-open"></i>' => Yii::t('onlinehelp','View Item'),
                        '<i class="icon-pencil"></i>' => Yii::t('onlinehelp','Update Item'),
                        '<i class="icon-remove"></i>' => Yii::t('onlinehelp','Remove Item'),
                        '<i class="icon-th-list"></i>' => Yii::t('onlinehelp','Manage Items'),
                        '<i class="icon-th-large"></i>' => Yii::t('onlinehelp','List Items'),
                    ),
                    //Yii::t('onlinehelp','App. Pages') => $pages,
                ),
            )); ?>
            <?php echo CHtml::error($model,'content'); ?>    
        </div>
    </div>
               
    <div class="control-group">
        <?php echo CHtml::activeLabelEx($model,'content',array('class'=>'control-label')); ?>
        <div class="controls">
            <?php $this->widget('application.extensions.ddeditor-bs.DDEditor',array(
                'model'=>$model,
                'attribute'=>'content',
                'previewRequest'=>'/post/preview',
                'htmlOptions'=>array('rows'=>7,'cssClass'=>'span6','style'=>'font-family:Courier', 'title'=>Yii::t('blog','Enter the content text (you may use Mardown syntax)') ),
                'additionalSnippets'=>array(
                    Yii::t('onlinehelp','Icons')=>array(
                        '<i class="icon-star"></i>' => Yii::t('onlinehelp','Create New Item'),
                        '<i class="icon-eye-open"></i>' => Yii::t('onlinehelp','View Item'),
                        '<i class="icon-pencil"></i>' => Yii::t('onlinehelp','Update Item'),
                        '<i class="icon-remove"></i>' => Yii::t('onlinehelp','Remove Item'),
                        '<i class="icon-th-list"></i>' => Yii::t('onlinehelp','Manage Items'),
                        '<i class="icon-th-large"></i>' => Yii::t('onlinehelp','List Items'),
                    ),
                    //Yii::t('onlinehelp','App. Pages') => $pages,
                ),
            )); ?>
            <?php echo CHtml::error($model,'content'); ?>    
        </div>
    </div>
    <div class="control-group">
        <?php echo $form->labelEx($model,'tags',array('class'=>'control-label required')); ?>
        <div class="controls">
        <?php $this->widget('CAutoComplete', array(
            'model'=>$model,
            'attribute'=>'tags',
            'url'=>array('suggestTags'),
            'multiple'=>true,
            'htmlOptions'=>array('class'=>'span5'),
        )); ?>
        <p class="hint">Please separate different tags with commas.</p>
        <?php echo $form->error($model,'tags'); ?>
        </div>
    </div>

    <?php echo $form->dropDownListRow($model,'status',Lookup::items('PostStatus')); ?>

    <div class="form-actions">
        <?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'submit', 'type'=>'primary', 'icon'=>'ok', 'label'=>$model->isNewRecord ? Yii::t('blog','Create') : Yii::t('blog','Save'))); ?>
        <?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'reset', 'icon'=>'repeat', 'label'=>Yii::t('site','Reset'))); ?>
    </div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/post/_view.php
<div class="post">
    <div class="header">
        <div class="title">
            <?php echo CHtml::link(CHtml::encode($data->title), $data->url); ?>
        </div>
        <div class="author">
            <?php echo CHtml::encode(Yii::t('blog','posted by {username} on {create_time}',array('{username}'=>$data->author->username, '{create_time}'=>Yii::app()->dateFormatter->formatDateTime($data->create_time,'full','short')))); ?>
        </div>
    </div>
    <div class="intro">
        <?php
            $this->beginWidget('CMarkdown', array('purifyOutput'=>true));
            echo $data->intro;
            $this->endWidget();
        ?>
    </div>
    <div class="content">
        <?php
            $this->beginWidget('CMarkdown', array('purifyOutput'=>true));
            echo $data->content;
            $this->endWidget();
        ?>
    </div>
    <div class="nav">
        <b><?php echo CHtml::encode(Yii::t('blog','Tags:')); ?></b>
        <?php echo implode(', ', $data->tagLinks); ?>
        <br/>
        <?php echo CHtml::link(Yii::t('blog','Permalink'), $data->url); ?> |
        <?php echo CHtml::link(Yii::t('blog','Comments').' ('.$data->commentCount.')',$data->url.'#comments'); ?> |
        <?php echo CHtml::encode(Yii::t('blog','Last updated on {update_time}',array('{update_time}'=>Yii::app()->dateFormatter->formatDateTime($data->update_time,'full','short')))); ?>
    </div>
</div>

protected/views/post/admin.php
<?php
$this->breadcrumbs=array(
    Yii::t('blog','Posts')=>array('index'),
    Yii::t('blog','Manage'),
);
$this->menu = array(
    array('label'=>Yii::t('blog','Create New Post'),'icon'=>'star', 'url'=>array('create')),
    array('label'=>Yii::t('blog','Posts Index'),'icon'=>'th-large', 'url'=>array('index')),
);
?>
<h1><?php echo CHtml::encode(Yii::t('blog','Manage Posts')) ?></h1>

<?php $this->widget('bootstrap.widgets.TbGridView', array(
    'type'=>'striped bordered condensed',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'columns'=>array(
        array(
            'class'=>'bootstrap.widgets.TbButtonColumn',
            'template'=>'{view}{update}',
        ),
        array(
            'name'=>'title',
            'type'=>'raw',
            'value'=>'CHtml::link(CHtml::encode($data->title), $data->url)'
        ),
        array(
            'name'=>'status',
            'value'=>'Post::model()->statusOptions[$data->status]',
            'filter'=>Post::model()->statusOptions,
        ),
        array(
            'name'=>'create_time',
            'type'=>'datetime',
            'filter'=>false,
        ),
        array(
            'class'=>'bootstrap.widgets.TbButtonColumn',
            'template'=>'{delete}',
        ),
    ),
)); ?>

protected/views/post/create.php
<?php
$this->breadcrumbs=array(
    Yii::t('blog','Posts')=>array('index'),
    Yii::t('blog','Create Post'),
);
$this->menu = array(
    array('label'=>Yii::t('blog','Posts Index'),'icon'=>'th-large', 'url'=>array('index')),
    array('label'=>Yii::t('blog','Manage Posts'),'icon'=>'th-list', 'url'=>array('admin')),
);
?>
<h1><?php echo CHtml::encode(Yii::t('blog','Create Post')) ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/post/date.php
<h1>Posts Issued on <i><?php echo CHtml::encode(date('F j, Y',$theDay)); ?></i></h1>

<?php foreach($posts as $post): ?>
<?php $this->renderPartial('_view',array(
	'data'=>$post,
)); ?>
<?php endforeach; ?>

<br/>
<?php $this->widget('CLinkPager',array('pages'=>$pages)); ?>

protected/views/post/found.php
<?php if(!empty($_GET['tag'])): ?>
<h1>Posts Tagged with <i><?php echo CHtml::encode($_GET['tag']); ?></i></h1>
<?php endif; ?>
<?php if(!empty($search->string)): ?>
<h1>Posts Searched by <i><?php echo CHtml::encode($search->string); ?></i></h1>
<?php endif; ?>

<?php foreach($posts as $post): ?>
<?php
	$pizza = explode('>', $post->content);
	$s = '';
	for ($i = 0; $i < count($pizza); $i++) {
		$piece = explode('<', $pizza[$i]);
		$replace = preg_replace('/('.$search->string.')/i', '<b><span style="background:yellow;">${1}</span></b>', $piece[0]);
		if (count($piece) == 2) {
			$s .= $replace.'<'.$piece[1].'>';
		} else if (count($piece) == 1) {
			$s .= $replace;
		}
	}
	$post->content = $s;

	$this->renderPartial('_view',array(
		'data'=>$post,
	));
?>
<?php endforeach; ?>

<br/>
<?php $this->widget('CLinkPager',array('pages'=>$pages)); ?>

protected/views/post/index.php
<?php
$this->pageTitle = Yii::app()->params['appTitle'];
$this->addMetaProperty('og:title', 'Blog Posts');
$this->addMetaProperty('og:type', 'website');
$this->addMetaProperty('og:url', $this->createUrl('index'));
//$this->addMetaProperty('og:image', Yii::app()->request->getBaseUrl(true).'/images/bootstrap-avatar_normal.png');
$this->addMetaProperty('og:site_name', Yii::app()->name);
//$this->addMetaProperty('og:locale',Yii::app()->fb->locale);
//$this->addMetaProperty('fb:app_id', Yii::app()->fb->appID);

$this->breadcrumbs=array(
    Yii::t('blog','Posts'),
);
$this->menu = array(
    array('label'=>Yii::t('blog','Create New Post'),'icon'=>'star', 'url'=>array('create')),
    array('label'=>Yii::t('blog','Manage Posts'),'icon'=>'th-list', 'url'=>array('admin')),
);
?>

<?php $this->beginWidget('bootstrap.widgets.TbHeroUnit', array(
    'heading'=>Yii::app()->name,
)); ?>
    <p>
        This is the Yii Blog Demo (see <a href="http://www.yiiframework.com/doc/blog/">Building a Blog System using Yii</a>).
    </p>
<?php $this->endWidget(); ?>

<?php if(!empty($_GET['tag'])): ?>
<h1><?php echo sprintf(CHtml::encode(Yii::t('blog','Posts Tagged with %s')),'<i>'.CHtml::encode($_GET['tag']).'</i>'); ?></h1>
<?php endif; ?>

<?php $this->widget('zii.widgets.CListView', array(
    'dataProvider'=>$dataProvider,
    'itemView'=>'_view',
    'template'=>"{items}\n{pager}",
)); ?>

protected/views/post/month.php
<h1><?php echo CHtml::encode(Yii::t('blog', 'Posts Issued in {month}', array('{month}'=>date('F, Y', $firstDay)))); ?></h1>

<?php foreach($posts as $post): ?>
<?php $this->renderPartial('_view',array(
	'data'=>$post,
)); ?>
<?php endforeach; ?>

<br/>
<?php $this->widget('CLinkPager',array('pages'=>$pages)); ?>